version: "3.7"

services:
  coffee_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "coffee_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "rootpwd"
    expose:
      - 5432
    ports:
      - "5432:5432"
  app:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - coffee_db